import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/ui/footer";
import { Navbar } from "@/components/ui/navbar";
import { NavLink } from "@/components/ui/link";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Estructura de la pagina "layout"
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-mono", jetbrainsMono.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Navbar
        contiene nav links dentro*/}
        <Navbar>
          <NavLink href="/" variant="hover">
            Inicio
          </NavLink>

          <NavLink href="/about" variant="hover">
            Sobre nosotros
          </NavLink>

          <NavLink href="/contact" variant="hover">
            Contacto
          </NavLink>
        </Navbar>
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
